### ISSUE TITLE
Button Padding

### ISSUE THREAD

**Issue by adunham95** [DamGapStudios/AshleyTLee.com#15]
Number, or more details needed

**Comment by AmGarera** [comment]
20px I believe

**Comment by adunham95** [comment]
Is this on all buttons, or just the nav bar? or just on the box?

**Comment by AmGarera** [comment]
Buttons as far as I've been told.
________________________________

**Comment by adunham95** [comment]
So All buttons

**Comment by AmGarera** [comment]
Yes

________________________________
