### ISSUE TITLE
Fixed nav bar

### ISSUE THREAD

**Issue by adunham95** [DamGapStudios/AshleyTLee.com#16]
Fixed nav bar on the top
Transparency when it scrolled down

**Comment by AmGarera** [comment]
http://thewonderjam.com/services/ for reference on desktop*

**Comment by adunham95** [comment]
On desktop only?

**Comment by AmGarera** [comment]
Both


________________________________

**Comment by adunham95** [comment]
Issue #5

**Comment by adunham95** [comment]
Added a static desktop header

**Comment by AmGarera** [comment]
Client accepts
