### ISSUE TITLE
Clickable Items in canvas element

### ISSUE THREAD

**Issue by adunham95** [DamGapStudios/AshleyTLee.com#2]

**Comment by adunham95** [comment]
Need to know where the all the pictures lin too

**Comment by AmGarera** [comment]
Portrait goes to about, phone to contact

**Comment by adunham95** [comment]
Is that it?
Or is there an entire list I dont have...

**Comment by AmGarera** [comment]
That's what I know off the top of my head


________________________________

**Comment by adunham95** [comment]
List of links still needed
