### ISSUE TITLE
Contact page on submit 

### ISSUE THREAD

**Issue by adunham95** [DamGapStudios/AshleyTLee.com#24]
When the contact page submit button is clicked the data should go somewhere

**Comment by AmGarera** [comment]
After looking at what's existing in there it looks like she's just using contact form 7(plugin) to have it send to her email after the form is filled out so any solution that would do that or hooking into contact form 7's rest api works to. In the end this is flexible and any solution that is easy for the user to fill out should be taken.

**Comment by adunham95** [comment]
I can tie it into that rest api. That looks like it will be the easiest way to do it

**Comment by AmGarera** [comment]
Sounds good

**Comment by AmGarera** [comment]
Closing this since it was addressed in #27
