### ISSUE TITLE
When loading the blog the logo is unavailable

### ISSUE THREAD

**Issue by adunham95** [DamGapStudios/AshleyTLee.com#26]
When reloading the blog page the image is not available
`GET http://ashleytlee.dev/blog/wp-content/themes/AshleyTLeeTheme/dist/ashley_logo.png 404 (Not Found)`

**Comment by adunham95** [comment]
When reloading the page it goes from url.com/blog to url.com/blog/ causing the file path from the image to not be correct

**Comment by adunham95** [comment]
When reloading the page something is adding /blog/ in the image url cause the logo to not have the right file path

**Comment by adunham95** [comment]
Issue persists when changing the component that is is loading

**Comment by AmGarera** [comment]
Was this always an issue or just occurred recently?

**Comment by adunham95** [comment]
I just noticed it recently. I dont know how long it was persisting

**Comment by adunham95** [comment]
Fix: 
Set the path to literally anything except /blog and the logo with load
