### ISSUE TITLE
Prayer request book component

### ISSUE THREAD

**Issue by adunham95** [DamGapStudios/AshleyTLee.com#35]
Banner for prayer request book, amazon links

**Comment by adunham95** [comment]
Need design documentation

**Comment by adunham95** [comment]
Add on home page
Below app
As tall as click here

**Comment by adunham95** [comment]
Issue with font. We do not have access to that web font
We need a fallback font

**Comment by adunham95** [comment]
Need the amazon link

**Comment by AmGarera** [comment]
Will provide this


________________________________

**Comment by AmGarera** [comment]
https://www.amazon.com/Prayer-Request-Book-Ashley-Lee/dp/B01N5AYH69
