### ISSUE TITLE
Get Designs

### ISSUE THREAD

**Issue by adunham95** [DamGapStudios/AshleyTLee.com#4]
- [x] Home Page
- [x] About Page
- [x] Messages Page
- [x] App Page
- [x] Events Page 
- [x] Contact Page
- [x] Blog Page
- [ ]  Giving Page
- [x]  Prayer Request Component

**Comment by AmGarera** [comment]
Added contact form to Google Docs Sheet, for now I'll check that as the contact page

**Comment by AmGarera** [comment]
Giving page is MIA, client not caring, closing for now
