### ISSUE TITLE
NavBar Issues

### ISSUE THREAD

**Issue by adunham95** [DamGapStudios/AshleyTLee.com#44]
- [x] Add Hamburger Icon
- [x] Add spacing between Social Media Icons
- [x] Make social Media Icons twice as large
- [x] Add Icons to nav Bar pages

**Comment by adunham95** [comment]
According to the emails I currently have there is no hamburger icon

**Comment by AmGarera** [comment]
Use the Unicode one until otherwise said

**Comment by adunham95** [comment]
Google Chrome doesnt support the Unicode navbar icon

**Comment by AmGarera** [comment]
Yes it does, I used it for a site

________________________________

**Comment by adunham95** [comment]
Do you mind adding it then? I might have been doing it wrong

**Comment by AmGarera** [comment]
Yeah I can do that

________________________________
